<a href="https://colab.research.google.com/github/arnavsaxena027/BadmintonMatchPrediction/blob/main/Project1(Playerprediction).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
# @title Importing all the requirements (all libraries and api and frameworks)

import tensorflow as tf
#imported tensor flow
import numpy as np
#this is a mathematical library
import pandas as pd
#this is for managing our dataset
import sklearn
import keras
#imported scikit-learn and Keras for the gradient boosting algorithm
from sklearn.ensemble import GradientBoostingClassifier
#this imports the Gradient boosting classifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
#this imports the system that measures the capacity of the model

this block works


In [45]:
# @title Importing the datasets
import pandas as pd

MenSingle = pd.read_csv("/content/drive/MyDrive/Badplayer/MenSingle.csv")
WomenSingle = pd.read_csv("/content/drive/MyDrive/Badplayer/WomenSingleT.csv")
BWFRanking = pd.read_csv("/content/drive/MyDrive/Badplayer/bwf_ranking.csv")

In [46]:
# @title Convering all the data into readable form for GB
#NOW WILL CONVERT ALL THE STRINGS TO FLOAT FOR READABLITY FOR ALGO
from sklearn.preprocessing import LabelEncoder
LabelEncoder_x = LabelEncoder()
a=['city', 'country', 'tournament_type','round','retired','team_one_players','team_two_players','team_one_nationalities','team_two_nationalities', 'winner']
for i in a:
  MenSingle[i] = LabelEncoder_x.fit_transform(MenSingle[i])
  WomenSingle[i] = LabelEncoder_x.fit_transform(WomenSingle[i])

#NOW WE WILL MAKE SURE THE ALGO DOES'NT CONSIDER DIFFERENT FLOATS ARE DIFFERNT NUMBERS(won't assume 1>2)
from sklearn.preprocessing import OneHotEncoder
OneHotEncoder_z = OneHotEncoder()
OneHotEncoder_z.fit_transform(MenSingle.city.values.reshape(-1,1)).toarray()
OneHotEncoder_z.fit_transform(MenSingle.country.values.reshape(-1,1)).toarray()
OneHotEncoder_z.fit_transform(MenSingle.tournament_type.values.reshape(-1,1)).toarray()
OneHotEncoder_z.fit_transform(MenSingle.retired.values.reshape(-1,1)).toarray()
OneHotEncoder_z.fit_transform(MenSingle.team_one_players.values.reshape(-1,1)).toarray()
OneHotEncoder_z.fit_transform(MenSingle.team_two_players.values.reshape(-1,1)).toarray()
OneHotEncoder_z.fit_transform(MenSingle.team_one_nationalities.values.reshape(-1,1)).toarray()
OneHotEncoder_z.fit_transform(MenSingle.team_two_nationalities.values.reshape(-1,1)).toarray()

OneHotEncoder_z.fit_transform(WomenSingle.city.values.reshape(-1,1)).toarray()
OneHotEncoder_z.fit_transform(WomenSingle.country.values.reshape(-1,1)).toarray()
OneHotEncoder_z.fit_transform(WomenSingle.tournament_type.values.reshape(-1,1)).toarray()
OneHotEncoder_z.fit_transform(WomenSingle.retired.values.reshape(-1,1)).toarray()
OneHotEncoder_z.fit_transform(WomenSingle.team_one_players.values.reshape(-1,1)).toarray()
OneHotEncoder_z.fit_transform(WomenSingle.team_two_players.values.reshape(-1,1)).toarray()
OneHotEncoder_z.fit_transform(WomenSingle.team_one_nationalities.values.reshape(-1,1)).toarray()
OneHotEncoder_z.fit_transform(WomenSingle.team_two_nationalities.values.reshape(-1,1)).toarray()

#changing all the cells which dont have numerical input to "Nan"
MenSingle= MenSingle.apply(pd.to_numeric, errors='coerce')
WomenSingle= WomenSingle.apply(pd.to_numeric, errors='coerce')

#NOW WILL CONVERT ALL THE FACTORS IN RANGE FOR THE ALGO
#from sklearn.preprocessing import StandardScaler
#stsc_z = StandardScaler()
#MenSingle = stsc_z.fit_transform(MenSingle)
#WomenSingle = stsc_z.fit_transform(WomenSingle)


#print(MenSingle)

In [ ]:
# @title Splitting data into dependable and indepedent variables
from pandas.core.dtypes.missing import notnull
# @title Splitting data into dependent and independent variables
import pandas as pd

# Split data for MenSingle
Men_independent = MenSingle[['city', 'country', 'tournament_type', 'round', 'retired', 'team_one_players', 'team_two_players', 'team_one_nationalities', 'team_two_nationalities']].values
Men_dependent = MenSingle[['winner']].values

# Split data for WomenSingle
Women_independent = WomenSingle[['city', 'country', 'tournament_type', 'round', 'retired', 'team_one_players', 'team_two_players', 'team_one_nationalities', 'team_two_nationalities']].values
Women_dependent = WomenSingle[['winner']].values
print(Men_independent)


In [ ]:
# @title Splitting data into train and test
#Spliting the data into train and test
from sklearn.model_selection import train_test_split

Men_independent_train, Men_independent_test, Men_dependent_train, Men_dependent_test = train_test_split(Men_independent,Men_dependent, test_size = 0.2,random_state = 0)
Women_dependent_train, Women_dependent_test, Women_independent_train, Women_independent_test = train_test_split(Women_dependent,Women_independent, test_size = 0.2,random_state = 0)

Models

In [60]:
Model1 = GradientBoostingClassifier(n_estimators=300,learning_rate=0.05,random_state=100,max_features=5)
#Model 1 using scikit-learn
Model1.fit(Men_independent_train, Men_dependent_train)
prediction1 = Model1.predict(Men_independent_test)
acc = accuracy_score(Men_dependent_test, prediction1)
print(acc)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.6321381142098274


In [61]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier
model_RF = RandomForestClassifier(n_estimators = 64, random_state = 2, max_depth = None, min_samples_split = 2, min_samples_leaf= 1)

model_RF.fit(Men_independent_train, Men_dependent_train)

prediction_RF = model_RF.predict(Men_independent_test)

accuracy_RF = accuracy_score(Men_dependent_test, prediction1)
conf_matrix = confusion_matrix(Men_dependent_test, prediction1)

print(f'Accuracy : {accuracy_RF*100}')
print(f'Confusion matrix : \n{conf_matrix}')

<ipython-input-61-de48ad5fe178>:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model_RF.fit(Men_independent_train, Men_dependent_train)


Accuracy : 63.213811420982736
Confusion matrix : 
[[ 12   0   0]
 [  0 244 129]
 [  0 148 220]]
